### ISSUE TITLE
FIFO workers not sending NewRelic instrumentation to ResqueJob

### ISSUE THREAD

**Issue by andoy** [jedld/resque-fifo-queue#1]
FIFO Workers are able to process the payload job just fine but it doesn't send instrumentation data to NewRelic. NewRelic instruments resque workers by default, it would be great if fifo-workers also do the same.

**[Works but no Instrumentation]**
rake resque:fifo-workers

**[Works with Instrumentation]**
rake resque:workers

**Comment by jedld** [comment]
Wow @andoy nice catch!, should be fixed in the next release
